name: hello_world
description: "Crockery Manager Pro - A professional UI converted from HTML."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- UI Icons & Fonts ---
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.7.0

  # --- NEW: CAMERA (Asli Camera Access Karne Ke Liye) ---
  camera: ^0.11.3

  # --- NEW: AI & Database (Offline System) ---
  # 1. AI Model run karne ke liye
  tflite_flutter: ^0.12.1
  
  # 2. Image process karne ke liye (Resize/Crop)
  image: ^4.1.3
  
  # 3. Offline Database (Fast Storage)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # 4. Storage Path (Files Save Karne Ke Liye)
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0
  
  # --- NEW: Code Generators (Database Code Banane Ke Liye) ---
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  # Assets Section (Images & Models)
  assets:
    - assets/logo.png
    - assets/mobilenet_v2.tflite  # <--- Yeh file 'assets' folder mein honi chahiye